export const DISHES =
    [
        {
        id: 0,
        category: 'Breakfast',
        cuisine: 'Italian',
        name:'Italian Brunch Torte',
        image: '/assets/images/ItalianBrunchTorte.jpg',
        label:'Hot',
        price:'80',
        featured: true,
        description:'Aliquip dolor incididunt anim culpa Lorem commodo incididunt excepteur velit labore ea id.'                    
        },
        {
        id: 1,
        category: 'Breakfast',
        cuisine: 'Italian',
        name:'Italian Baked Eggs & Saucalico-pepper-frittatasage',
        image: '/assets/images/Italian-Baked-Eggs-Sausage.jpg',
        label:'Hot',
        price:'100',
        featured: false,
        description:"Officia dolor qui in reprehenderit ut culpa id amet minim reprehenderit."
        },
        {
        id: 2,
        category: 'Breakfast',
        cuisine: 'Italian',
        name:'calico-pepper-frittata',
        image: '/assets/images/Calico Pepper Frittata.jpg',
        label:'New',
        price:'140',
        featured: false,
        description:'Eu sit Lorem eiusmod consectetur Id sunt aute enim aliqua nostrud excepteur sit ea non enim consequat..'
        },
        {
        id: 3,
        category: 'Breakfast',
        cuisine: 'Italian',
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Aute qui deserunt nisi ullamco irure sint adipisicing ut aliquip.'
        },
        {
        id: 4,
        category: 'Breakfast',
        cuisine: 'Italian',
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Fugiat aliquip ex cillum incididunt cupidatat adipisicing nostrud.'
        },
        
        {
        id: 5,
        category: 'Lunch/Dinner',
        subcategory: "Starters",
        cuisine: 'Italian',
        name:'Vitello Tonnato',
        image: '/assets/images/VitelloTonnato.jpg',
        label:'Hot',
        price:'80',
        featured: true,
        description:'Aliquip dolor incididunt anim culpa Lorem commodo incididunt excepteur velit labore ea id.'                    
        },
        {
        id: 6,
        category: 'Lunch/Dinner',
        subcategory: "Starters",
        cuisine: 'Italian',
        name:'Antipasti',
        image: '/assets/images/antipasti.jpg',
        label:'Hot',
        price:'100',
        featured: true,
        description:"Officia dolor qui in reprehenderit ut culpa id amet minim reprehenderit."
        },
        {
        id: 7,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Starters",
        name:'Arancini Cakes',
        image: '/assets/images/arancini-cakes.jpg',
        label:'New',
        price:'140',
        featured: false,
        description:'Eu sit Lorem eiusmod consectetur Id sunt aute enim aliqua nostrud excepteur sit ea non enim consequat..'
        },
        {
        id: 8,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Starters",
        name:' Cheese Garlic Bread',
        image: '/assets/images/garlic-bread.jpg',
        label:'hot',
        price:'199',
        featured: false,
        description:'Aute qui deserunt nisi ullamco irure sint adipisicing ut aliquip.'
        },
        {
        id: 9,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Starters",
        name:'Burrata-Tomato Salad',
        image: '/assets/images/burrata-tomato-salad.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Fugiat aliquip ex cillum incididunt cupidatat adipisicing nostrud.'
        },
        {
        id: 10,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Starters",
        name:'Carrot and Ginger Soup',
        image: '/assets/images/carrot-and-ginger-soup.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 11,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Starters",
        name:'Herb and Almond Soup with Cheese Muffin',
        image: '/assets/images/herb-and-almond-soup-cheese-muffin-loaf.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 12,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 13,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 14,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 15,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 16,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 17,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pasta",
        name:'Frittata Florentine',
        image: '/assets/images/frittata-florentine.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 18,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Classic Margherita',
        image: '/assets/images/Classic-Margherita.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 19,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Farmhouse Overload',
        image: '/assets/images/Farmhouse-Overload.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 20,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Tandoori Paneer',
        image: '/assets/images/Tandoori-Paneer.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 21,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Tangy Chaat Pizza',
        image: '/assets/images/Tangy Chaat Pizza.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 22,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Mexican Veggie Delight',
        image: '/assets/images/Mexican Veggie Delight.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        },
        {
        id: 23,
        category: 'Lunch/Dinner',
        cuisine: 'Italian',
        subcategory: "Pizza",
        name:'Jalapeno Capsicum delight',
        image: '/assets/images/Jalapeno Capsicum delight.jpg',
        label:'',
        price:'199',
        featured: false,
        description:'Eu irure nostrud sit duis excepteur nostrud qui nostrud consequat irure ad.'
        }
    ];